language: python
sudo: false
python:
  - "2.7"

install:
  - "travis_retry pip install coveralls"
  - "travis_retry pip install git+git://github.com/TurboGears/tg2.git@development"
  - "travis_retry pip install -e .[testing]"

script: "python setup.py nosetests"

after_success:
  coveralls
